projects:
  default:
    config:
      assumeValidSDL: true
      assumeValid: true
    schema:
      # - https://graphql.pomelosolutions.com
      # - test.gql
      - http://localhost:3600/graphql
    documents: src/**/*.tsx
    extensions:
      codegen:
        generates:
          schema.graphql:
            plugins:
              - schema-ast
          ./src/generated/gql.types.generated.ts:
            plugins:
              - typescript
            config:
              namingConvention:
                enumValues: keep
                typeNames: change-case#pascalCase
          ./src/generated/:
            preset: client
            presetConfig:
              fragmentMasking:
                unmaskFunctionName: "getFragmentData"
