name: pomelo_app

on:
  push:
    branches: [main]

jobs:
  Deploy:
    name: Deploy to pomelo_app

    runs-on: ubuntu-latest

    steps:
      - name: build deploy

        uses: actions/checkout@v2

      - name: executing remote ssh commands

        uses: appleboy/ssh-action@v0.1.10

        with:
          host: ${{ secrets.SSH_HOST }}

          username: ${{ secrets.USER_NAME }}

          key: ${{ secrets.SSH_PRIVATE_KEY }}

          port: ${{ secrets.PORT }}

<<<<<<< HEAD
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd /home/pomelo/Projects/pomelo-app
            git pull
            npm install
            npm run build
            pm2 restart all
=======
        key: ${{ secrets.SSH_PRIVATE_KEY }}

        port: ${{ secrets.PORT }}

        script: |
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          cd /home/pomelo/Projects/pomelo-app
          git stash && git pull && npm install && npm run build
          pm2 restart all
          
>>>>>>> 1a65b9ffbd8d889c1feee376375bfeaf50678d16
